export const saucelabsbackpack = '#item_4_title_link > .inventory_item_name'
export const bolttshirt = '#item_1_title_link > .inventory_item_name'
export const saucelabsbikelight = '#item_0_title_link > .inventory_item_name'
export const jacket = '#item_5_title_link > .inventory_item_name'
export const onesie = '#item_2_title_link > .inventory_item_name'
export const tshirt = '#item_3_title_link > .inventory_item_name'
export const addsaucelab = '[data-test="add-to-cart-sauce-labs-backpack"]'
export const addbolt = '[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]'
export const addlight = '[data-test="add-to-cart-sauce-labs-bike-light"]'
export const addjacket = '[data-test="add-to-cart-sauce-labs-fleece-jacket"]'
export const addonesie = '[data-test="add-to-cart-sauce-labs-onesie"]'
export const addtshirt = '[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]'
export const cartButton = '.shopping_cart_link'
export const checkoutButton = '[data-test="checkout"]'
export const firstnameField = '[data-test="firstName"]'
export const lastnameField = '[data-test="lastName"]'
export const postcodeField = '[data-test="postalCode"]'
export const continueButton = '[data-test="continue"]'
export const finishButton = '[data-test="finish"]'
export const thanksorder = '.complete-header'